### ISSUE TITLE
cx_Freeze

### ISSUE THREAD

**Issue by kkernan** [Rexeh/joystick-diagrams#72]
I get this error running on a new windows 11 machine.

---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\Users\RCox\AppData\Local\pypoetry\Cache\virtualenvs\joystick-diagrams-Gl6OzfeB-py3.10\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
  File "C:\Users\RCox\AppData\Local\pypoetry\Cache\virtualenvs\joystick-diagrams-Gl6OzfeB-py3.10\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "src\joystick_diagrams.py", line 5, in <module>
  File "C:\Users\RCox\Documents\GitHub\joystick-diagrams-2\src\adaptors\dcs_world.py", line 4, in <module>
  File "C:\Users\RCox\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 14, in <module>
ModuleNotFoundError: No module named 'urllib'

**Comment by Rexeh** [comment]
This is related to python version, you shouldn't need to use CX freeze unless you're packaging exe for distribution.

This is handled by my CI pipeline.

**Comment by kkernan** [comment]
I have python 3.10.7, what version do I need to use?
